name=GS32WIFI
version=1.0.0
author=pimmik98
maintainer=GS32Bios
sentence=A comprehensive library for managing Wi-Fi modes (OFF, STA, AP, AP+STA) on ESP32 in Arduino IDE.
deprecate=false
architectures=esp32
category=Communication
url=https://github.com/
includes=GS32WIFI.h
